#!/usr/bin/env python
import rospy
import random
from std_msgs.msg import Int32
n = 0

def cb(message):
    rospy.loginfo(message.data)
    ra = random.choice(list)
    print ra

if __name__ == '__main__': 
    #n = 
    list = [1,2,3,4,5]
    while not rospy.is_shutdown():
        #while n < 1:
        rospy.init_node('twice')
        sub = rospy.Subscriber('count_up', Int32, cb)
        n += 1
        print n
        #rospy.spin()
        if n == 5:
            print "finish"  
        rospy.spin()
